openapi: 3.0.0
info:
  version: "1.0.0"
  title: Score Management API
  contact:
    email: anand.anmol150@gmail.com
    
paths:
  /score:
    post:
      summary: saves score
      operationId: app.store_score
      description: Saves a score from our quiz game
      responses:
        '201':
          description: score saved
        '400':
          description: 'invalid input, object invalid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Score'
        description: Score to save
  /leaderboard:
    get:
      summary: gets top 10 scores for the leaderboard
      operationId: app.get_top_scores
      responses:
        '200':
          description: Sucessfully returned 10 scores
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Score'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: string
      

components:
  schemas:
    Score:
      type: object
      required:
        - name
        - score
      properties:
        name:
          type: string
          example: 'Anmol'
        score:
          type: integer
          example: 3